// Default Material List Database
const DEFAULT_COMPANIES = [
  { name: "GUNGE", circle: "", status: "Active" }
];

const DEFAULT_MATERIALS = [
  { code: "1", description: "Waste tiny cut pcs of Fabrics", price: 15.0, unit: "kg" },
  { code: "2", description: "Waste carton", price: 11.0, unit: "kg" },
  { code: "3", description: "Waste Paper roll/cone", price: 14.0, unit: "kg" },
  { code: "4", description: "Waste Polythine", price: 20.0, unit: "kg" },
  { code: "5", description: "Waste Wood", price: 5.0, unit: "kg" },
  { code: "6", description: "Waste thread", price: 15.0, unit: "kg" },
  { code: "7", description: "Waste elastic", price: 15.0, unit: "kg" },
  { code: "8", description: "Waste elastic & thread", price: 15.0, unit: "kg" },
  { code: "9", description: "Waste broken hanger", price: 15.0, unit: "kg" },
  { code: "10", description: "Empty jerry can/(Big/small)", price: 80.0, unit: "pcs" },
  { code: "11", description: "Empty Steel Drum (Big)", price: 400.0, unit: "pcs" },
  { code: "12", description: "Empty steel drum (medium)", price: 320.0, unit: "pcs" },
  { code: "13", description: "Empty steel silicate drum", price: 420.0, unit: "pcs" },
  { code: "14", description: "Empty plastic drum (small)", price: 220.0, unit: "pcs" },
  { code: "15", description: "Empty steel drum (small)", price: 160.0, unit: "pcs" },
  { code: "16", description: "Waste p.p belt", price: 15.0, unit: "kg" },
  { code: "17", description: "Waste belt cover", price: 12.5, unit: "kg" },
  { code: "18", description: "Waste poly chat", price: 12.5, unit: "kg" },
  { code: "19", description: "Waste steel wire", price: 15.0, unit: "kg" },
  { code: "20", description: "Empty plastic container", price: 100.0, unit: "pcs" },
  { code: "21", description: "Empty plastic drum (medium)", price: 320.0, unit: "pcs" }
];

// Translation Dictionary for English and Bengali
const TRANSLATIONS = {
  bn: {
    title: "কাস্টমস শুল্কায়ন ব্যবস্থাপক",
    subtitle: "Customs Assessment Template",
    dashboard: "ড্যাশবোর্ড",
    assessment: "শুল্কায়ন শীট",
    materials: "মালামাল তালিকা",
    settings: "সেটিংস",
    companyName: "প্রতিষ্ঠানের নাম",
    hasFileNo: "নথি নং থাকবে?",
    filePageNo: "নথি পাতা নং",
    noteParaNo: "নোটানুচ্ছেদ নং",
    letterPageNo: "পত্র পাতা নং",
    bepzaRecNo: "বেপজা সুপারিশ নং",
    yes: "হ্যাঁ",
    no: "না",
    searchPlaceholder: "কোড বা বিবরণ দিয়ে খুঁজুন...",
    addNewItem: "নতুন আইটেম যোগ করুন",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল",
    edit: "সম্পাদনা",
    delete: "মুছুন",
    totalItems: "মোট মালামাল প্রকার",
    totalAssessableVal: "সর্বমোট শুল্কায়ন মূল্য (টাকা)",
    totalDutyTax: "সর্বমোট শুল্ক-করাদি (টাকা)",
    inWords: "কথায় : ",
    takaOnly: " টাকা মাত্র।",
    printBtn: "প্রিন্ট (A4)",
    exportBtn: "এক্সেল",
    exportHtml: "HTML ফাইল",
    exportPdf: "PDF ফাইল",
    importBtn: "ডাটা ইম্পোর্ট",
    saveAssessment: "সেভ করুন",
    saveHistory: "সংরক্ষিত ফাইল",
    whatsappShare: "WhatsApp শেয়ার",
    resetBtn: "সব মুছুন (Reset)",
    formulaSettings: "হিসাব সূত্র সেটিংস",
    standardBDFormula: "বাংলাদেশ কাস্টমস সূত্র (ভ্যাট ও এটি স্তরীভূত)",
    simplePercentFormula: "সরল শতকরা সূত্র (সরাসরি শুল্কায়ন মূল্যের উপর)",
    taxRates: "ডিফল্ট ট্যাক্স রেট (%)",
    insuranceRate: "ডিফল্ট ইন্সুরেন্স চার্জ (%)",
    landingRate: "ডিফল্ট ল্যান্ডিং চার্জ (%)",
    // Table Headers
    sl: "ক্র. নং",
    approveCode: "অনুমোদন নথির ক্রমিক নং",
    description: "বিবরণ",
    unitPrice: "ইউনিট মূল্য (টাকা)",
    unit: "একক",
    qty: "পরিমাণ",
    totalPrice: "সর্বমোট মূল্য (টাকা)",
    insurance: "ইন্সুরেন্স চার্জ",
    landing: "ল্যান্ড চার্জ",
    assessableVal: "শুল্কায়ন মূল্য (টাকা)",
    cd: "সিডি",
    rd: "আরডি",
    sd: "এসডি",
    vat: "মূসক",
    ait: "এআইটি",
    at: "এটি",
    dutyTax: "শুল্ক-করাদি (টাকা)",
    action: "অ্যাকশন",
    total: "মোট",
    signatures: "সাক্ষরসমূহ",
    preparedBy: "প্রস্তুতকারী",
    checkedBy: "যাচাইকারী",
    approvedBy: "অনুমোদনকারী কাস্টমস কর্মকর্তা"
  },
  en: {
    title: "Customs Assessment Manager",
    subtitle: "Customs Assessment Template",
    dashboard: "Dashboard",
    assessment: "Assessment Sheet",
    materials: "Materials Database",
    settings: "Settings",
    companyName: "Organization Name",
    hasFileNo: "File No. Exist?",
    filePageNo: "File Page No.",
    noteParaNo: "Note Paragraph No.",
    letterPageNo: "Letter Page No.",
    bepzaRecNo: "BEPZA Recommend No.",
    yes: "Yes",
    no: "No",
    searchPlaceholder: "Search code or description...",
    addNewItem: "Add New Item",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    totalItems: "Total Item Types",
    totalAssessableVal: "Total Assessable Value (BDT)",
    totalDutyTax: "Total Duty & Taxes (BDT)",
    inWords: "In Words: ",
    takaOnly: " Taka Only.",
    printBtn: "Print (A4)",
    exportBtn: "Export CSV",
    exportHtml: "Export HTML",
    exportPdf: "Export PDF",
    importBtn: "Import Data",
    saveAssessment: "Save",
    saveHistory: "Saved History",
    whatsappShare: "WhatsApp Share",
    resetBtn: "Reset All",
    formulaSettings: "Calculation Formula Settings",
    standardBDFormula: "BD Customs Standard (VAT/AT Compounded)",
    simplePercentFormula: "Simple Percentage (Direct on Assessable Value)",
    taxRates: "Default Tax Rates (%)",
    insuranceRate: "Default Insurance Charge (%)",
    landingRate: "Default Landing Charge (%)",
    // Table Headers
    sl: "Sl. No",
    approveCode: "Approve Code",
    description: "Description",
    unitPrice: "Unit Price (Tk)",
    unit: "Unit",
    qty: "Qty",
    totalPrice: "Total Price (Tk)",
    insurance: "Insurance",
    landing: "Landing Charge",
    assessableVal: "Assessable Value (Tk)",
    cd: "CD",
    rd: "RD",
    sd: "SD",
    vat: "VAT",
    ait: "AIT",
    at: "AT",
    dutyTax: "Duty & Taxes (Tk)",
    action: "Action",
    total: "Total",
    signatures: "Signatures",
    preparedBy: "Prepared By",
    checkedBy: "Checked By",
    approvedBy: "Approving Customs Officer"
  }
};

// Export variables if environment supports node modules, otherwise let them exist globally
if (typeof module !== "undefined" && module.exports) {
  module.exports = { DEFAULT_COMPANIES, DEFAULT_MATERIALS, TRANSLATIONS };
}
