-- ============================================================
-- Customs Assessment Manager — Supabase Database Migration Schema
-- Developed by: Md. Yusuf Ali
-- ============================================================

-- 1. Create Assessments Table
CREATE TABLE IF NOT EXISTS public.assessments (
    id TEXT PRIMARY KEY,
    company_name TEXT NOT NULL,
    assessment_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    rows_data JSONB NOT NULL DEFAULT '[]'::jsonb,
    total_assessable_value NUMERIC(15, 2) DEFAULT 0,
    total_duty_tax NUMERIC(15, 2) DEFAULT 0,
    header_info JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Create Companies Table
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    circle TEXT,
    status TEXT DEFAULT 'Active',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Create Materials Table
CREATE TABLE IF NOT EXISTS public.materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(12, 2) DEFAULT 0,
    unit TEXT DEFAULT 'kg',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;

-- Create Policies to allow public read/write access with Anon Key
CREATE POLICY "Allow public all access on assessments" ON public.assessments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all access on companies" ON public.companies FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all access on materials" ON public.materials FOR ALL USING (true) WITH CHECK (true);
