-- ============================================================
-- Customs Assessment Manager — Supabase Database Migration Schema
-- Developed by: Md. Yusuf Ali
-- ============================================================

-- 1. Create Assessments Table
CREATE TABLE IF NOT EXISTS public.assessments (
    id TEXT PRIMARY KEY,
    company_name TEXT NOT NULL,
    assessment_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    rows_data JSONB NOT NULL DEFAULT '[]'::jsonb,
    total_assessable_value NUMERIC(15, 2) DEFAULT 0,
    total_duty_tax NUMERIC(15, 2) DEFAULT 0,
    header_info JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Create Companies Table
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    circle TEXT,
    status TEXT DEFAULT 'Active',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Create Materials Table
CREATE TABLE IF NOT EXISTS public.materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(12, 2) DEFAULT 0,
    unit TEXT DEFAULT 'kg',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Secure each record to the authenticated Supabase user.
-- Run this migration in the Supabase SQL Editor before enabling cloud sync.
ALTER TABLE public.assessments ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

-- Company and material names/codes are unique per user, not globally.
ALTER TABLE public.companies DROP CONSTRAINT IF EXISTS companies_name_key;
ALTER TABLE public.materials DROP CONSTRAINT IF EXISTS materials_code_key;
CREATE UNIQUE INDEX IF NOT EXISTS companies_user_name_key ON public.companies (user_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS materials_user_code_key ON public.materials (user_id, code);

ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;

-- Remove the insecure policies from the previous schema.
DROP POLICY IF EXISTS "Allow public all access on assessments" ON public.assessments;
DROP POLICY IF EXISTS "Allow public all access on companies" ON public.companies;
DROP POLICY IF EXISTS "Allow public all access on materials" ON public.materials;

CREATE POLICY "Users manage own assessments" ON public.assessments
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users manage own companies" ON public.companies
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users manage own materials" ON public.materials
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
